### ISSUE TITLE
setting binary mode by default

### ISSUE THREAD

**Issue by BrianHicks** [assert-rs/snapbox#299]
hi! I'm using trycmd to test a utility that generates source code. As part of that, I need `\` to not be escaped. Hypothetically, I could use binary mode to accomplish this, but I'm also testing that the invocations in my README are valid, and I don't see anything in the docs that will let me set binary mode. So: can we have a flag on `TestCases` or similar to set binary mode by default, please?

By the way, it took me an unpleasant amount of time to begin to suspect the test harness was mangling my output. If it were up to me, that wouldn't be the default. I get why it's there (from reading #91) and that it's probably too late to change, but documentation in the `trycmd` crate would have helped. Would you be open to a PR to say what's going on there? (Or, really, for any of this?)

**Comment by epage** [comment]
While not global, you can set `binary` on a per-test basis
https://github.com/assert-rs/snapbox/blob/62ce68decd010b3727700ff04660642ac7c8d42e/crates/trycmd/schema.json#L72-L75

Something I've been considering with structured data support is how to expose control over it, including opting in and opting out, see #93

As this has a lot of overlap with #93, I lean towards closing this and centralizing the conversation there so we can come up with a solution that keeps both use cases in mind.  If there is a reason you think this should be kept open separately, let us know!

**Comment by BrianHicks** [comment]
I know I can set it on a per-test basis, but not in a Markdown file… unless I've misunderstood something?

**Comment by BrianHicks** [comment]
actually, I tried this just now and it doesn't look like it works. The backslashes in my output are still being converted to forward slashes. Here's the TOML file I'm using; does it look right to you?

```
bin.name = "elm-duet"
args = ["schema.json"]
binary = true
```

**Comment by epage** [comment]
Oh right, that only controls the programs input/output.

I'm working some of the underpinings for trycmd at the
