### ISSUE TITLE
Bug in `assert_matches` deprecation message

### ISSUE THREAD

**Issue by smoelius** [assert-rs/snapbox#327]
Currently, it says:
https://github.com/assert-rs/snapbox/blob/60703c95dd57758100a287686926cdba737ccef8/crates/snapbox/src/lib.rs#L200
I think it should say something like the following?
```
Replaced with `assert_data_eq!(expected, actual)`
                               ^^^^^^^^^^
```

**Comment by smoelius** [comment]
I know it's a little bikesheddy, but can I ask why you went with the `actual, expected` order?

**Comment by epage** [comment]
I personally prefer `(actual, expected)` asserts (and `if` conditions) but our output is of the model `diff expected actual` which suggests `(expected, actual)`, so I think that is why `(expected, actual)` was used.  This came up again in #226 and that was enough to push me over the edge to switch them but I still go back and forth.

**Comment by smoelius** [comment]
Thank you vey much for your reply.
